apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeserver
  labels:
    app: nodeserver
spec:
  selector:
    matchLabels:
      app: nodeserver
  replicas: 1
  template:
    metadata:
      labels:
        app: nodeserver   # Matching the selector label
    spec:
      containers:
        - name: nodeserver
          image: thislucasme/hello-node:v5
          envFrom:
            - configMapRef:
                name: nodeserver-env
