apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeserver
  labels:
    app: nodeserver
spec:
  selector:
    matchLabels:
      app: nodeserver
  replicas: 1
  template:
    metadata:
      labels:
        app: nodeserver   # Matching the selector label
    spec:
      containers:
        - name: nodeserver
          image: thislucasme/hello-node:v5.1
          livenessProbe:
            httpGet:
              path: /helthz
              port: 8000
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 1
            successThreshold: 1
          envFrom:
            - configMapRef:
                name: nodeserver-env
          volumeMounts:
            - mountPath: "/myfamily"
              name: config
      
      volumes:
        - name: config
          configMap: 
            name: configmap-family
            items:
            - key: members
              path: "myfamily.txt"