apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeserver
  labels:
    app: nodeserver
spec:
  selector:
    matchLabels:
      app: nodeserver
  replicas: 1
  template:
    metadata:
      labels:
        app: nodeserver   # Matching the selector label
    spec:
      containers:
        - name: nodeserver
          image: thislucasme/hello-node:v5.6
          resources:
            requests:
              cpu: "0.3"
              memory: 20Mi
            limits:
              cpu: "0.3"
              memory: 25Mi 
          # startupProbe:
          #   httpGet:
          #     path: /helthz
          #     port: 4343
          #   periodSeconds: 3
          #   failureThreshold: 30
          #   timeoutSeconds: 1
          #   successThreshold: 1

          # readinessProbe:
          #   httpGet:
          #     path: /helthz
          #     port: 4343
          #   periodSeconds: 3
          #   failureThreshold: 1
          #   timeoutSeconds: 1
          #   successThreshold: 1
            #initialDelaySeconds: 10

          # livenessProbe:
          #   httpGet:
          #     path: /helthz
          #     port: 4343
          #   periodSeconds: 5
          #   failureThreshold: 1
          #   timeoutSeconds: 1
          #   successThreshold: 1
            #initialDelaySeconds: 15
          envFrom:
            - configMapRef:
                name: nodeserver-env
          volumeMounts:
            - mountPath: "/myfamily"
              name: config
            - mountPath: "/node/pvc"
              name: nodeserver-volume
      
      volumes:
        - name: nodeserver-volume
          persistentVolumeClaim:
            claimName: nodeserver-pvc 
        - name: config
          configMap: 
            name: configmap-family
            items:
            - key: members
              path: "myfamily.txt"