apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata: 
  name: nodeserver-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    name: nodeserver
    kind: Deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 25
