apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nodeserver
  labels:
    app: nodeserver
spec:
  selector:
    matchLabels:
      app: nodeserver
  replicas: 3
  template:
    metadata:
      labels:
        app: nodeserver   # Matching the selector label
    spec:
      containers:
        - name: nodeserver
          image: thislucasme/hello-node:v3
