apiVersion: v1
kind: Service
metadata:
  name: nodeserver-server
spec:
  selector:
    app: nodeserver
  type: LoadBalancer
  ports:
  - name: nodeserver-service
    port: 4545
    targetPort: 4343
    protocol: TCP